In [1]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")

# 1.1 Create a 1D array with numbers from 0 to 99
arr1_1 = np.arange(100)

# 1.2 Create a 3x3 array filled with ones
arr1_2 = np.ones((3, 3))

# 1.3 Create a 2x4 array filled with 7
arr1_3 = np.full((2, 4), 7)

# 1.4 Create a 5x5 array with random integers between 10 and 50
arr1_4 = np.random.randint(10, 51, size=(5, 5))


print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])

--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[11 13 13 19 17]
 [36 38 15 45 44]]


In [2]:
# Task 2: Indexing and Slicing with Arrays
print("\n--- Task 2: Indexing and Slicing with Arrays ---")

data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])

# 2.1 Extract element at row 2, column 3 (0-indexed)
val2_1 = data[2, 3]

# 2.2 Extract the first row
row2_2 = data[0, :]

# 2.3 Extract the last column
col2_3 = data[:, -1]

# 2.4 Extract rows 1 and 2, columns 0 and 1
sub_arr2_4 = data[1:3, 0:2]

# 2.5 Boolean indexing: select elements greater than 100
filtered_elements2_5 = data[data > 100]


print("val2_1:", val2_1)
print("row2_2:", row2_2)
print("col2_3:", col2_3)
print("sub_arr2_4:\n", sub_arr2_4)
print("filtered_elements2_5:", filtered_elements2_5)


--- Task 2: Indexing and Slicing with Arrays ---
val2_1: 120
row2_2: [10 20 30 40]
col2_3: [ 40  80 120 160]
sub_arr2_4:
 [[ 50  60]
 [ 90 100]]
filtered_elements2_5: [110 120 130 140 150 160]


In [3]:
# Task 3: Conditional Operations
print("\n--- Task 3: Conditional Operations ---")

arr3_1 = np.random.randint(1, 21, size=(4, 5))  # Random 4x5 array with values 1 to 20

# 3.1 Replace elements less than 10 with 0, keep others unchanged
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

# 3.2 Count even elements in arr3_1
even_count3_3 = np.sum(arr3_1 % 2 == 0)


print("arr3_1:\n", arr3_1)
print("\narr3_2 (values < 10 replaced by 0):\n", arr3_2)
print("\nCount of even elements:", even_count3_3)


--- Task 3: Conditional Operations ---
arr3_1:
 [[16 10 15 15 12]
 [ 4 19  1 15 14]
 [17 10  1  7 19]
 [18  5 17 16  8]]

arr3_2 (values < 10 replaced by 0):
 [[16 10 15 15 12]
 [ 0 19  0 15 14]
 [17 10  0  0 19]
 [18  0 17 16  0]]

Count of even elements: 9


In [4]:
# Task 4: Aggregation Functions
print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])

# 4.1 Sum of all elements
sum4_1 = np.sum(arr4_1)

# 4.2 Mean of each column
mean_cols4_2 = np.mean(arr4_1, axis=0)

# 4.3 Maximum value in each row
max_rows4_3 = np.max(arr4_1, axis=1)

# 4.4 Standard deviation of the entire array
std4_4 = np.std(arr4_1)


print("arr4_1:\n", arr4_1)

print("\nSum of all elements:", sum4_1)
print("Mean of each column:", mean_cols4_2)
print("Maximum value in each row:", max_rows4_3)
print("Standard deviation:", std4_4)


--- Task 4: Aggregation Functions ---
arr4_1:
 [[10  5 12]
 [ 3  8 15]
 [20  7  4]]

Sum of all elements: 84
Mean of each column: [11.          6.66666667 10.33333333]
Maximum value in each row: [12 15 20]
Standard deviation: 5.2493385826745405


In [5]:
# Task 5: Reshaping and Flattening
print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)   # 1D array from 0 to 23

# 5.1 Reshape into 4x6 2D array
reshaped_arr5_2 = arr5_1.reshape(4, 6)

# 5.2 Reshape into 2x3x4 3D array
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

# 5.3 Flatten back into 1D array using ravel()
flattened_arr5_4 = reshaped_arr5_2.ravel()

# Using flatten() for comparison
flattened_arr5_5 = reshaped_arr5_2.flatten()


print("Original arr5_1:")
print(arr5_1)

print("\nReshaped 4x6 array:")
print(reshaped_arr5_2)

print("\nReshaped 2x3x4 array:")
print(reshaped_arr5_3)

print("\nFlattened using ravel():")
print(flattened_arr5_4)

print("\nFlattened using flatten():")
print(flattened_arr5_5)


--- Task 5: Reshaping and Flattening ---
Original arr5_1:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Reshaped 4x6 array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Reshaped 2x3x4 array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Flattened using ravel():
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Flattened using flatten():
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [6]:
# Task 6: Broadcasting
print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

scalar = 10
vector = np.array([100, 200, 300])


# 6.1 Add scalar to every element of arr6_1
arr6_2 = arr6_1 + scalar

# 6.2 Add vector to each row of arr6_1 (broadcasting)
arr6_3 = arr6_1 + vector


print("Original array:")
print(arr6_1)

print("\nAfter adding scalar 10:")
print(arr6_2)

print("\nAfter adding vector [100, 200, 300]:")
print(arr6_3)


--- Task 6: Broadcasting ---
Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

After adding scalar 10:
[[11 12 13]
 [14 15 16]
 [17 18 19]]

After adding vector [100, 200, 300]:
[[101 202 303]
 [104 205 306]
 [107 208 309]]


In [7]:
# 6.1 Add the 'scalar' to every element of 'arr6_1'
result6_1 = arr6_1 + scalar

# 6.2 Add the 'vector' to each row of 'arr6_1'
result6_2 = arr6_1 + vector


print("result6_1 (arr6_1 + scalar):")
print(result6_1)

print("\nresult6_2 (arr6_1 + vector):")
print(result6_2)

result6_1 (arr6_1 + scalar):
[[11 12 13]
 [14 15 16]
 [17 18 19]]

result6_2 (arr6_1 + vector):
[[101 202 303]
 [104 205 306]
 [107 208 309]]


In [8]:
# Task 7: Copying vs. Viewing Arrays
print("\n--- Task 7: Copying vs. Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])

# 7.1 Create a view using slicing
view_arr7 = original_arr7[:]

# Modify the first element of view
view_arr7[0] = 99

print("View array after modification:")
print(view_arr7)

print("Original array after view modification:")
print(original_arr7)


# 7.2 Create a copy using .copy()
copy_arr7 = original_arr7.copy()

# Modify the last element of copy
copy_arr7[-1] = 0

print("\nCopy array after modification:")
print(copy_arr7)

print("Original array after copy modification:")
print(original_arr7)


--- Task 7: Copying vs. Viewing Arrays ---
View array after modification:
[99  2  3  4  5]
Original array after view modification:
[99  2  3  4  5]

Copy array after modification:
[99  2  3  4  0]
Original array after copy modification:
[99  2  3  4  5]


In [12]:
# Task 8: Stacking and Splitting Arrays
print("\n--- Task 8: Stacking and Splitting Arrays ---")

arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])

# 8.1 Vertically stack arr8_a and arr8_b
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))

# 8.2 Horizontally stack arr8_a and arr8_b
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))

# 8.3 Vertically stack vstack_arr8_1 and arr8_c
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

# 8.4 Split combined_arr8_3 into 3 parts
part1, part2, part3 = np.array_split(combined_arr8_3, 3)


# Display results
print("vstack_arr8_1:")
print(vstack_arr8_1)

print("\nhstack_arr8_2:")
print(hstack_arr8_2)

print("\ncombined_arr8_3:")
print(combined_arr8_3)

print("\npart1:")
print(part1)

print("\npart2:")
print(part2)

print("\npart3:")
print(part3)

print("\nCombined array:")
print(combined_arr8_3)

print("\nPart 1:")
print(part1)

print("\nPart 2:")
print(part2)

print("\nPart 3:")
print(part3)


--- Task 8: Stacking and Splitting Arrays ---
vstack_arr8_1:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack_arr8_2:
[[1 2 5 6]
 [3 4 7 8]]

combined_arr8_3:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

part1:
[[1 2]
 [3 4]]

part2:
[[5 6]
 [7 8]]

part3:
[[ 9 10]]

Combined array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

Part 1:
[[1 2]
 [3 4]]

Part 2:
[[5 6]
 [7 8]]

Part 3:
[[ 9 10]]


In [13]:
# Task 9: Sorting and Searching
print("\n--- Task 9: Sorting and Searching ---")

arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])

arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])


# 9.1 Sort arr9_1 in ascending order
sorted_arr9_1 = np.sort(arr9_1)


# 9.2 Sort arr9_2d along columns
sorted_cols9_2 = np.sort(arr9_2d, axis=0)


# 9.3 Find indices where value 9 is present in arr9_1
idx9_3 = np.where(arr9_1 == 9)


# 9.4 Find index of maximum value in arr9_1
max_idx9_4 = np.argmax(arr9_1)


print("Original arr9_1:")
print(arr9_1)

print("\nSorted arr9_1:")
print(sorted_arr9_1)

print("\nOriginal arr9_2d:")
print(arr9_2d)

print("\nColumn-wise sorted arr9_2d:")
print(sorted_cols9_2)

print("\nIndex where value 9 is present:")
print(idx9_3)

print("\nIndex of maximum value:")
print(max_idx9_4)


--- Task 9: Sorting and Searching ---
Original arr9_1:
[5 2 8 1 9 4 7 3 6]

Sorted arr9_1:
[1 2 3 4 5 6 7 8 9]

Original arr9_2d:
[[30 20 10]
 [60 50 40]
 [90 80 70]]

Column-wise sorted arr9_2d:
[[30 20 10]
 [60 50 40]
 [90 80 70]]

Index where value 9 is present:
(array([4]),)

Index of maximum value:
4
