In [2]:
# Your code for Task 1 here:
import pandas as pd
import numpy as np
# 1.1 Create a Pandas Series
s1_1 = pd.Series([10, 20, 30, 40, 50])

print("Series s1_1:")
print(s1_1)

# 1.2 Create a 3x4 NumPy array with random integers between 1 and 100
np_array1_2 = np.random.randint(1, 101, size=(3, 4))

print("\nNumPy Array np_array1_2:")
print(np_array1_2)

# 1.3 Convert the NumPy array to a Pandas DataFrame
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

print("\nDataFrame df1_3:")
print(df1_3)

Series s1_1:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array np_array1_2:
[[59 21  4 52]
 [13 67 81 26]
 [55 77 55  5]]

DataFrame df1_3:
    A   B   C   D
0  59  21   4  52
1  13  67  81  26
2  55  77  55   5


In [3]:
# Task 2: Synthetic Data Generation for Practice
print("\n--- Task 2: Synthetic Data Generation for Practice ---")

import pandas as pd
import numpy as np

# For reproducible results
np.random.seed(42)

# Create DataFrame
df_sales = pd.DataFrame({
    'Date': pd.date_range(start='2023-01-01', periods=100, freq='D'),
    'Region': np.random.choice(['East', 'West', 'North', 'South'], size=100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], size=100),
    'Sales': np.random.randint(100, 1001, size=100),
    'Quantity': np.random.randint(1, 11, size=100)
})

# Introduce NaN values

# 5 random NaN values in Sales
sales_nan_idx = np.random.choice(df_sales.index, size=5, replace=False)
df_sales.loc[sales_nan_idx, 'Sales'] = np.nan

# 3 random NaN values in Quantity
quantity_nan_idx = np.random.choice(df_sales.index, size=3, replace=False)
df_sales.loc[quantity_nan_idx, 'Quantity'] = np.nan

# Display first few rows
print("\nFirst 10 rows:")
print(df_sales.head(10))

# Check missing values
print("\nMissing values per column:")
print(df_sales.isna().sum())


--- Task 2: Synthetic Data Generation for Practice ---

First 10 rows:
        Date Region   Product  Sales  Quantity
0 2023-01-01  North  Keyboard  674.0       7.0
1 2023-01-02  South     Mouse  963.0       4.0
2 2023-01-03   East     Mouse    NaN       7.0
3 2023-01-04  North   Monitor  340.0       8.0
4 2023-01-05  North     Mouse  663.0       1.0
5 2023-01-06  South     Mouse  195.0       6.0
6 2023-01-07   East     Mouse  999.0       8.0
7 2023-01-08   East   Monitor  833.0       5.0
8 2023-01-09  North     Mouse  584.0       4.0
9 2023-01-10   West  Keyboard  506.0       2.0

Missing values per column:
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64


In [4]:
# Task 3: Indexing and Slicing in DataFrames
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")

# Use 'df_sales' from Task 2

# 3.1 Select only the 'Region' and 'Sales' columns
df3_1 = df_sales[['Region', 'Sales']]

print("\n3.1 Region and Sales columns:")
print(df3_1.head())


# 3.2 Select rows where Product is 'Laptop'
df3_2 = df_sales[df_sales['Product'] == 'Laptop']

print("\n3.2 Rows where Product = Laptop:")
print(df3_2.head())


# 3.3 Select rows where Region is 'East' AND Sales > 500
df3_3 = df_sales[
    (df_sales['Region'] == 'East') &
    (df_sales['Sales'] > 500)
]

print("\n3.3 Rows where Region = East and Sales > 500:")
print(df3_3.head())


# 3.4 Select the Sales value for the first entry where Product is 'Monitor'

monitor_rows = df_sales.loc[df_sales['Product'] == 'Monitor']

if not monitor_rows.empty:
    val3_4 = monitor_rows.iloc[0]['Sales']
    print("\n3.4 First Sales value where Product = Monitor:")
    print(val3_4)
else:
    val3_4 = None
    print("\nNo Monitor records found.")


--- Task 3: Indexing and Slicing in DataFrames ---

3.1 Region and Sales columns:
  Region  Sales
0  North  674.0
1  South  963.0
2   East    NaN
3  North  340.0
4  North  663.0

3.2 Rows where Product = Laptop:
         Date Region Product  Sales  Quantity
16 2023-01-17  South  Laptop  624.0       4.0
19 2023-01-20  North  Laptop  798.0      10.0
21 2023-01-22   East  Laptop  185.0       3.0
24 2023-01-25  South  Laptop  781.0       4.0
27 2023-01-28   West  Laptop  745.0       8.0

3.3 Rows where Region = East and Sales > 500:
         Date Region  Product  Sales  Quantity
6  2023-01-07   East    Mouse  999.0       8.0
7  2023-01-08   East  Monitor  833.0       5.0
30 2023-01-31   East  Monitor  719.0       8.0
31 2023-02-01   East   Laptop  655.0       1.0
35 2023-02-05   East   Laptop  739.0       7.0

3.4 First Sales value where Product = Monitor:
340.0


In [5]:
# Task 4: Data Cleaning (Handling Missing Values)
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")

# Use 'df_sales' from Task 2

# 4.1 Check missing values in each column
missing_counts4_1 = df_sales.isna().sum()

print("\n4.1 Missing values per column:")
print(missing_counts4_1)


# 4.2 Fill missing Sales values with the mean of Sales column
df4_2_filled = df_sales.copy()

sales_mean = df4_2_filled['Sales'].mean()

df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(sales_mean)

print("\n4.2 Missing values after filling Sales:")
print(df4_2_filled['Sales'].isna().sum())


# 4.3 Drop rows that contain any missing values
df4_3_dropped = df_sales.dropna()

print("\n4.3 Shape after dropping rows with missing values:")
print(df4_3_dropped.shape)


# Optional verification
print("\nRemaining missing values after dropna():")
print(df4_3_dropped.isna().sum())


--- Task 4: Data Cleaning (Handling Missing Values) ---

4.1 Missing values per column:
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

4.2 Missing values after filling Sales:
0

4.3 Shape after dropping rows with missing values:
(92, 5)

Remaining missing values after dropna():
Date        0
Region      0
Product     0
Sales       0
Quantity    0
dtype: int64


In [6]:
# Task 5: Data Manipulation (Columns, Sorting, Grouping)
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")

# Use 'df_sales' (the original one with NaNs)

# 5.1 Create a new column 'Total_Revenue'
# NaN values automatically propagate

df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']

print("\n5.1 DataFrame with Total_Revenue:")
print(df_sales[['Sales', 'Quantity', 'Total_Revenue']].head())


# 5.2 Sort by Date (ascending) and then Sales (descending)

df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)

print("\n5.2 Sorted DataFrame:")
print(df5_2_sorted.head())


# 5.3 Group by Region and calculate sum of Sales and Quantity

df5_3_grouped_region = df_sales.groupby('Region')[
    ['Sales', 'Quantity']
].sum()

print("\n5.3 Total Sales and Quantity by Region:")
print(df5_3_grouped_region)


# 5.4 Group by Product and find average Sales

df5_4_grouped_product = df_sales.groupby('Product')[
    'Sales'
].mean()

print("\n5.4 Average Sales by Product:")
print(df5_4_grouped_product)


--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---

5.1 DataFrame with Total_Revenue:
   Sales  Quantity  Total_Revenue
0  674.0       7.0         4718.0
1  963.0       4.0         3852.0
2    NaN       7.0            NaN
3  340.0       8.0         2720.0
4  663.0       1.0          663.0

5.2 Sorted DataFrame:
        Date Region   Product  Sales  Quantity  Total_Revenue
0 2023-01-01  North  Keyboard  674.0       7.0         4718.0
1 2023-01-02  South     Mouse  963.0       4.0         3852.0
2 2023-01-03   East     Mouse    NaN       7.0            NaN
3 2023-01-04  North   Monitor  340.0       8.0         2720.0
4 2023-01-05  North     Mouse  663.0       1.0          663.0

5.3 Total Sales and Quantity by Region:
          Sales  Quantity
Region                   
East    12564.0      88.0
North   12585.0     140.0
South   16136.0     133.0
West    14779.0     133.0

5.4 Average Sales by Product:
Product
Keyboard    593.066667
Laptop      554.360000
Monitor     561.3809